---
#
# Ansible managed
#
repository:
  description: Install and configure investigation tools on your system.
  homepage: https://buluma.co.ke/
  topics: investigate, ansible, molecule, tox, playbook, hacktoberfest
