---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '17 9 7,14,21 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.5
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "alpine"
            tag: "latest"
          - image: "amazonlinux"
            tag: "latest"
          # - image: "debian"   # TODO fatal: [investigate-debian-bookwormpy310-ansible-5]: FAILED! => {"changed": false, "msg": "No package matching 'net-tools' is available"}
          #  tag: "bookworm"
          - image: "fedora"
            tag: "rawhide"
          - image: "docker-ubuntu2204-ansible"    # TODO fatal: [investigate-ubuntu-latestpy310-ansible-5]: FAILED! => {"changed": false, "msg": "No package matching 'net-tools' is available"}
            tag: "latest"
          # - image: "ubuntu"    # TODO fatal: [investigate-ubuntu-bionicpy310-ansible-5]: FAILED! => {"changed": false, "msg": "No package matching 'net-tools' is available"}
          #  tag: "bionic"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: buluma/molecule-action@v4.0.5
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
